### ISSUE TITLE
Unsupported machine type: aarch64. Please run this script on a x86_64 machine

### ISSUE THREAD

**Issue by jason05031** [kugaevsky/outline-server-arm64#4]
root@instance-20220330-2007:~# sudo SB_IMAGE="kugaevsky/outline-server-arm64" bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
Unsupported machine type: aarch64. Please run this script on a x86_64 machine

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_logVG4

**Comment by kugaevsky** [comment]
Here is the solution — https://github.com/kugaevsky/outline-server-arm64/issues/3

**Comment by jason05031** [comment]
> Here is the solution — #3
thx！

**Comment by kugaevsky** [comment]
Updated server version and readme
