### ISSUE TITLE
无法连接到您的 Outline 服务器

### ISSUE THREAD

**Issue by jason05031** [kugaevsky/outline-server-arm64#5]
虽然您的 Outline 服务器已正确安装，但我们无法连接到该服务器。这很可能是因为该服务器的防火墙规则阻止接入连接。请检查防火墙规则，确保端口 1024 - 65535 均允许接入 TCP 连接。
root@instance-20220330-2007:/home/ubuntu# ufw status
Status: inactive

Oracle cloud Default Security List 
All traffic for all ports   ALLOWS

**Comment by kugaevsky** [comment]
You should open ports through iptables.
