### ISSUE TITLE
Here is the solution — https://github.com/kugaevsky/outline-server-arm64/issues/3

### ISSUE THREAD

**Issue by wlbdxc** [kugaevsky/outline-server-arm64#6]
Here is the solution — https://github.com/kugaevsky/outline-server-arm64/issues/3

_Originally posted by @kugaevsky in https://github.com/kugaevsky/outline-server-arm64/issues/4#issuecomment-1083110415_

Who can help me ?I don't understand any code, can someone teach me how to do it

**Comment by kugaevsky** [comment]
Updated server version and readme
